image:
  repository: dupsy/my-flask-time-app
  tag: 5d376427fc78f3e706a2a8dd5e7a649c227f24f9
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
