image:
  repository: dupsy/my-flask-time-app
  tag: 6f6647946050d2fd6c3ddd2d5d06447c7c1fb7f1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
