image:
  repository: dupsy/my-flask-time-app
  tag: 2c30ceda22bad0c0299b3c3dab08ca7f1bf76d40
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
