image:
  repository: dupsy/my-flask-time-app
  tag: 749ad1240804b1ccf5616277620e6265ddf9127f
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
