image:
  repository: dupsy/my-flask-time-app
  tag: dcf28f90cb4e0aaad769dac2e1ca28f339716ce3
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
