image:
  repository: dupsy/my-flask-time-app
  tag: 3fb8d989f1913d1f58c1ed69ed9e6a8afb840b5b
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
