image:
  repository: dupsy/my-flask-time-app
  tag: 5a935352c598b230f8a9da3bc796dc7bdcde93a6
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
