image:
  repository: dupsy/my-flask-time-app
  tag: a71911caaa803347667b18194e575ac7ebca52ca
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
