image:
  repository: dupsy/my-flask-time-app
  tag: 512964bd6753068b206349da95a9c2767df063e7
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
