image:
  repository: dupsy/my-flask-time-app
  tag: fd33acf9f7c9612941c6a73c7d694f099da8fb39
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
