image:
  repository: dupsy/my-flask-time-app
  tag: 62123b7546522b6c3801b65b1c07df261392d6da
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
