image:
  repository: dupsy/my-flask-time-app
  tag: 9310bb17acaf9b925dc28b0bf4e820fe2d06e8f8
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
