image:
  repository: dupsy/my-flask-time-app
  tag: 64399ec1cbaa25d863bba5589642603c58307d81
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
