image:
  repository: dupsy/my-flask-time-app
  tag: 56e4a7c60a9eefb92de913074997fb4f4d323e8c
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
