image:
  repository: dupsy/my-flask-time-app
  tag: 764c6301499af54209ca1b31ad60efcf3bdc18ac
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
