image:
  repository: dupsy/my-flask-time-app
  tag: 3069dbdf718bc609eda36fda9357f98517845a3a
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
