image:
  repository: dupsy/my-flask-time-app
  tag: 760368256188ace407f9b222c9d0dba2a7a95dc2
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
