image:
  repository: dupsy/my-flask-time-app
  tag: c466d880c10122051eccd81c0b1c6ec8ffde362b
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
