image:
  repository: dupsy/my-flask-time-app
  tag: fd66a475af4b99d5b37c28384016931bd85c4a93
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
