image:
  repository: dupsy/my-flask-time-app
  tag: a53016cdf2a5477a302cc4638190163b06c6d38d
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
